add_newline = true 

format = "$all"

[character]                            # The name of the module we are configuring is"character"
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[aws]
disabled = true
symbol = ""

[buf]
symbol = ""

[conda]
symbol = "🅒"

[dart]
symbol = ""

[directory]
truncation_length = 0
read_only = ""

[docker_context]
symbol = ""

[elixir]
symbol = ""

[elm]
symbol = ""

[git_branch]
symbol = ""

[golang]
symbol = ""

[haskell]
symbol = ""

[hg_branch]
symbol = ""

[java]
symbol = ""

[julia]
symbol = ""

[memory_usage]
symbol = ""

[nim]
symbol = ""

[nix_shell]
symbol = ""

[nodejs]
symbol = ""

[package]
symbol = ""

[rust]
symbol = ""

